version: "3.8"

networks:
  network:

volumes:
  dbb:
    driver: local

services:
  backend:
    build:
      context: .
      args:
        - COMMIT_HASH
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    networks:
      - network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: price-info
    volumes:
      - dbb:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5