version: "3.8"

networks:
  network:

volumes:
  dbb:
    driver: local

services:
  backend:
    build:
      context: .
      args:
        - COMMIT_HASH
    networks:
      - network
    ports:
      - 8000:80
    environment:
      OTEL_SERVICE_NAME: "backend"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger:4317"
    restart:
      on-failure
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    networks:
      - network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: price-info
    volumes:
      - dbb:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  jaeger:
    image: jaegertracing/all-in-one
    networks:
      - network
    ports:
      - 16686:16686
      - 4317:4317
    environment:
      - COLLECTOR_OTLP_ENABLED=true
