CREATE TABLE IF NOT EXISTS pricepoint (
  _time TIMESTAMP WITH TIME ZONE NOT NULL PRIMARY KEY,
  _price DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS emissions (
  _time TIMESTAMP WITH TIME ZONE NOT NULL PRIMARY KEY,
  _emission DECIMAL NOT NULL
);

