name: Deployment
run-name: Deployment by ${{ github.actor }}

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Delivery]
    types: [completed]

jobs:
  format_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 10.92.0.41
          username: ubuntu
          passphrase: ${{ secrets.STRATO_PEM }}
          script: whoami