name: Integration
run-name: Integration by ${{ github.actor }}

on:
  push:
  workflow_dispatch:

jobs:
  format_and_test:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: wattsdown
          python-version: "3.10"
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Pip install
        run: make req
      - name: Format
        shell: bash -l {0}
        run: make fmt
      - name: Lint
        shell: bash -l {0}
        run: make lint
      - name: Test
        shell: bash -l {0}
        run: make test